:Connect <NODEX>
USE [master]
GO
CREATE AVAILABILITY GROUP [<AGNAME>]
WITH (AUTOMATED_BACKUP_PREFERENCE = SECONDARY,
DB_FAILOVER = OFF,
DTC_SUPPORT = NONE,
REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 0)
FOR DATABASE [Database01]
REPLICA ON 

